name: Property Tests
on:
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write

concurrency:
  group: property-test
  cancel-in-progress: false

jobs:
  proptest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: NixOS/nix-installer-action@62c1943b776c509394b550f3f983adc14e9212d6 # v1.0.0
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: elixir-tools
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/.mise.toml') }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{ hashFiles('**/.mise.toml') }}-

      - name: Install Dependencies
        run: nix develop --command bash -c "mix deps.get"

      - name: Compile
        run: nix develop --command bash -c "MIX_ENV=test mix compile"

      - name: Run property tests
        env:
          GH_TOKEN: ${{ github.token }}
        run: nix develop --command bash -c "MIX_ENV=test mix test.json --only property | .github/property_failures.exs"
